### ISSUE TITLE
interval Plural not working properly.

### ISSUE THREAD

**Issue by boulepick** [i18next/i18next-intervalPlural-postProcessor#157]
first great plugin.
1st ) I belive the Documentation needs to be updated.
i18next.use(intervalPlural)  does not work, i get error not found. when i do i18next.use(i18nextIntervalPluralPostProcessor) i do not get an error.

2) when i try to do a postprocess i get an error in the console log.
here is my code

i18next 3.3.1
i18next-intervalPlural-postProcessor 0.2.3

i init like this

i18next
    .use(i18nextBrowserLanguageDetector)
    .use(i18nextXHRBackend)
    .use(Cache)
    .use(i18nextIntervalPluralPostProcessor)
    .init(i18nextoptions, function (err, t) {
        var options = $().jqueryI18nextOptions;
        //init jquery-i18next
        jqueryI18next.init(i18next, $,options);
......
.....
}

in my JSON file i have something like this
"validation":  {
   "progComplete" : "The $t(label.Plan) is empty.",
   "progComplete_plural" : "Great, the $t(label.Plan) is complete.",
   "progComplete_interval" : "(1-99){The  Plan is incomplete, {{count}} error(s) detected, please go back and validate the Plan.};(99-inf){\"test\"})",
...
}

now in my JS file i call it like in the documentation 

var progWrkMsg = $.t("validation.progComplete", {postProcess: 'interval', count: 2});

and the error in console log is like this:

_**i18next::translator: missingKey en translation validation.progComplete validation.progComplete.**_

now if  don't call : .use(i18nextIntervalPluralPostProcessor) or in my JS i do not include "postprocessor" like this : var progWrkMsg = $.t("validation.progComplete", {count: 2});

i do not get an error and get the plural of the key : "Great, the Plan is comnplete."

Thank you

**Comment by jamuhl** [comment]
should be `import intervalPlural from 'i18next-intervalplural-postprocessor'`all lowercased

call `var progWrkMsg = $.t("validation.progComplete_interval", {postProcess: 'interval', count: 2});` (_interval)
