### ISSUE TITLE
Regex Expression does not handle whitespace characters

### ISSUE THREAD

**Issue by ghost** [i18next/i18next-intervalPlural-postProcessor#203]
The current regex  - `/^\((\S*)\){(.*)}$/`

Will match each of the following statements twice when the string segments are split by `;`

`(0){zero};(1){single};`
`(a){zero};(Z){single};`

However after splitting the following statements by interval, it will not match:

`(0) {zero};(1) {single};`
`(0) {zero}; (1) {single};`

I might recommend a match which catches whitespaces or warn users when with an exception.

**Comment by jamuhl** [comment]
will see if we could support having whitespace in between...should not be a big deal...as they are pure formatting. Will look into it tomorrow.

**Comment by ghost** [comment]
It would be a nice touch. Although, I should mention that the real issue might be on Locize.io which adds spaces when using the Google Translate UI

(0){Take bus to};(1){Take bus 1 stop to}; => (0) {Prendre le bus vers}; (1) {Prendre le bus 1 jusqu'à};

**Comment by jamuhl** [comment]
;) i think extending the regex will be easier than asking google to change that

**Comment by jamuhl** [comment]
i18next-intervalplural-postprocessor@1.0.2 should now support this...

**Comment by jamuhl** [comment]
@josephmcasey was a long time ago...did the updated version work with whitespaces - or do i need to change the regex a little more to make it work?
