### ISSUE TITLE
How should Arabic numeric ranges with numeric count be supported?

### ISSUE THREAD

**Issue by ghost** [i18next/i18next-intervalPlural-postProcessor#204]
I recently tried using Locize.io with Gengo. I seem to have run into a limitation with the I18Next ecosystem.

```
**Arabic Intervals**

(0){دقيقة};
(1){دقيقة};
(2){دقيقتان};
(3-11){{{count}} دقائق};
(11-Inf){{{count}} دقيقة};

**English Intervals**

(0){0 minutes};
(1){1 minute};
(2-Inf){{{count}} minutes};
```

Is it expected that I expand English intervals in an unnatural way?

```
**English Intervals**

(0){0 minutes};
(1){1 minute};
(2){2 minutes};
(3-11){{{count}} minutes};
(11-Inf){{{count}} minutes};
```

I'm not too concerned with the extension of the English intervals above, but I am curious about whether or not this becomes problematic if there is a language that counts intervals 2-100 differently than Arabic when I am using English as my reference language.

**Comment by ghost** [comment]
I might also add that it would be nice if the recommended in this issue could be added to the I18Next plural documentation for others, or it could be a console warning when users like myself only add intervals for 0 or 1.

**Comment by jamuhl** [comment]
hm...not sure but for the case described above why not just using the regular plural?

https://www.i18next.com/plurals.html#languages-with-multiple-plurals

interval plurals fallback to regular plural if not having a value in the defined ranges. Basically the interval plurals are more to specify plural texts in form of "we got a few items" and "we have a lot of items"

regular plurals:

```
**Arabic**

"key_0" : "دقيقة"
"key_1": "دقيقة"
"key_2": "دقيقتان"
"key_3": "{{count}} دقائق"
"key_4": "{{count}} دقائق"
"key_5": "{{count}} دقيقة"

// -> not sure if the forms are are correct...but rules are here: https://www.i18next.com/plurals.html#how-to-find-the-correct-plural-suffix

**English**

"key": "{{count}} minute"
"key_plural": "count minutes"
```

**Comment by jamuhl** [comment]
the regular plural will also be automatically generated for other languages in locize - while we can't guess which intervals makes sense in other languages

**Comment by ghost** [comment]
I might be mistaken about everything you said, so correct me if I am wrong.

I think you're saying that, my reference language being English, I only require the following.

```
**English**

"key": "{{count}} minute"
"key_plural": "count minutes"
```

If and when I run into languages with more plurals forms than English, I have to manually maintain each of their various plural individually as a superset to the plurals my reference language supports like this?

```
**Arabic**

"key_0" : "دقيقة"
"key_1": "دقيقة"
"key_2": "دقيقتان"
"key_3": "{{count}} دقائق"
"key_4": "{{count}} دقائق"
"key_5": "{{count}} دقيقة"

"key": "{{count}} دقيقة"
"key_plural": "{{count}} دقيقة"
```

Or are you saying that I would intentionally not populate the values for my plural and implicit singular keys, having disparate keys depending on the plural forms support by each language like this:

```
**Arabic**

"key_0" : "دقيقة"
"key_1": "دقيقة"
"key_2": "دقيقتان"
"key_3": "{{count}} دقائق"
"key_4": "{{count}} دقائق"
"key_5": "{{count}} دقيقة"
```

**Comment by jamuhl** [comment]
the or:

en: key, key_plural will be automatically toggled to key_0, key_1,...key_5 in arabic:

<img width="1331" alt="screen shot 2017-10-25 at 20 59 05" src="https://user-images.githubusercontent.com/977772/32017601-80ece830-b9c7-11e7-9b0b-088688a2bb40.png">

**Comment by ghost** [comment]
Wow, I see.

It seems that I have misused the intended purpose of the interval post processor, and I was unaware that adding a language on Locize.io would add the plurals automatically.

Since the concept of "zero" in English is discussed inconsistently depending on the context, I utilized a count of "0 Minutes" to instead be represented as "< 1 Minute".

Unfortunately, that means the `_interval` key is added to Arabic where the concept of zero is handled perhaps more consistently, not that I would know.

I think the answer is that in languages with multiple plurals the interval keys are usually expected to only be represented in languages with only limited plural forms, like English.

**Comment by jamuhl** [comment]
honestly i got no idea...i can speak a few languages...but all come from roman or germanic language roots (german, english, french, italian)...so i really can't express what the multiple plurals in eg. arabic or russian express...neither why most asiatic languages not even have plural forms...all rather strange...;)

**Comment by jamuhl** [comment]
but yeah...interval might be more for the english, and similar languages to express zero, few, that might or not might be handled already in the other languages having multiple plurals...
