### ISSUE TITLE
Negative count and negative infinity

### ISSUE THREAD

**Issue by ahaverty** [i18next/i18next-intervalPlural-postProcessor#205]
Is it possible to catch negative values?
Preferably from negative infinity to zero i.e `-inf -> 0`

**I've tried:**
`(-inf-0){Lowest text to display}`
`(-1000-0){Lowest text to display}`
but they don't seem to catch.

**Comment by jamuhl** [comment]
no does not yet support negativ values...would be great....pull request welcome

**Comment by aqum** [comment]
Workaround for simple case with just matching negative numbers is to use `_plural` for negative text and rest in `_interval`. This plugins falls back to key without suffix if it doesn't find correct range.

```
translation: {
  key2: 'negative numbers',
  key2_interval: '(0-inf){positive numbers}'
};

i18next.t('key2_interval', { postProcess: 'interval', count: -10 }); // -> negative numbers
i18next.t('key2_interval`, { postProcess: 'interval', count: 0 }); // -> positive numbers
```

**Comment by ahaverty** [comment]
Smart @aqum , thanks for commenting
