### ISSUE TITLE
Can we support TS?

### ISSUE THREAD

**Issue by MeCKodo** [i18next/i18next-intervalPlural-postProcessor#207]
I just very needed

**Comment by jamuhl** [comment]
Currently the community is working on it -> react-i18next already got it's typedefinitions, i18next will get them added with next major version.

If you like you can add those typescript definitions for this package? I personally do not use typescript...so would have first to learn that proper before being able to do on my own.

PR very welcome 👍

**Comment by MeCKodo** [comment]
OK, Thank you very much.I will try.
