### ISSUE TITLE
Linebreak doesn't work

### ISSUE THREAD

**Issue by bobbybobby** [i18next/i18next-intervalPlural-postProcessor#208]
With this translation object

```
translation: {
  'LIKE_COUNT': '{{count}} person\nlikes this',
  'LIKE_COUNT_plural': '{{count}} people\nlike this',
  'LIKE_COUNT_interval': "(0){No one\nlikes this};"
}
```

And using

`t('LIKE_COUNT_interval', {postProcess: 'interval', count: 0})}`

It falls back to the plural rule. Also I had to guess what was failing by trial and error, it would be nice to have some log by `i18next-intervalPlural-postProcessor` when it can't parse the translation.

**Comment by jamuhl** [comment]
The awesomeness of OpenSource -> feel free to provide a PR

**Comment by jamuhl** [comment]
fix by @adrai published in i18next-intervalplural-postprocessor@1.0.3
