### ISSUE TITLE
Doesn't fallback to classic plural

### ISSUE THREAD

**Issue by Skriptach** [i18next/i18next-intervalPlural-postProcessor#210]
Given resources
```json
"upload": {
  "files": "{{count}} файл был загружен",
  "files_plural": "{{count}} файлов было загружено",
  "files_interval": "(2-4){ {{count}} файлa было загружено};"
}
```

Invoke t like this:
```javascript
const { count } = this.state;
...
t('upload.files_interval', { postProcess: 'interval', count })
```
Works fine for 2-4. But get `5 файл был загружен` instead of `5 файлов было загружено`

**Comment by jamuhl** [comment]
What ever language that is I guess it has more than one pluralform: https://www.i18next.com/translation-function/plurals#languages-with-multiple-plurals

and https://www.i18next.com/translation-function/plurals#how-to-find-the-correct-plural-suffix

**Comment by Skriptach** [comment]
Thank you.
