### ISSUE TITLE
Combine with context

### ISSUE THREAD

**Issue by wouterraateland** [i18next/i18next-intervalPlural-postProcessor#214]
I'm using `i18next` and there seems to be an issue with combining this post processor with contexts.

For example, given the following translation strings:
```json
{
  "joins": "joins",
  "joins_plural": "join",
  "joins_interval": "(0)nobody joins",
  "joins_past": "joined",
  "joins_past_plural": "joined",
  "joins_past_interval": "(0)nobody joined",
}
```

`t("joins_interval", {count: 1, context: "past", postProcess: "interval"})` returns `joined`,
but `t("joins_interval", {count: 0, context: "past", postProcess: "interval"})` returns `nobody joins`.

I would expect it to return `nobody joined` instead.

Am I missing something here?

**Comment by jamuhl** [comment]
You're accessing key `joins_interval` not using interval post processing!

so key with context not using interval would be `joins_interval_past` for  `t("joins_interval", {count: 0, context: "past"})`

Accessing interval would be something like: https://github.com/i18next/i18next-intervalPlural-postProcessor#usage-sample `i18next.t('key1_interval', { postProcess: 'interval', count: 1 });`

but not sure how you will have to mix this up with context - never used that myself...

**Comment by wouterraateland** [comment]
Ah sorry, forgot writing `postProcess: 'interval'` in the question. Edited it. I have for now settled on a custom solution without this package, but still it would be cool to see this package support contexts.

**Comment by jamuhl** [comment]
should be rather simple to get it working...PR welcome
