### ISSUE TITLE
Translation interval with the variable not working

### ISSUE THREAD

**Issue by nejcm** [i18next/i18next-intervalPlural-postProcessor#221]
## 🐛 Bug Report

Translation where the variable directly succeeds the { in the interval does not work.

## To Reproduce

In the example below the name wont be replaced when the count is 1 but it will fallback to the plural version.

Translation:
```json
  "hosts_interval": "(0){your hosts};(1){{{name}}};(2-inf){your hosts};",
```

Code:
```js
  const hostsText = t('hosts_interval', {
    name: 'John',
    postProcess: 'interval',
    count: 1,
  });
```

## Expected behavior

The variable should be parsed correctly and replaced.

## Your Environment

- *i18next version*: i.e. 19.8.4
- *i18next-intervalplural-postprocessor version*: i.e. 2.0.2

**Comment by jamuhl** [comment]
v3.0.0 **BREAKING** changes regex from `/\((\S*)\).*{((.|\n)*)}/` to `/\((\S*)\).*?\[((.|\n)*)\]/` -> from (condition){value} to (condition)[value] to fix [#206](https://github.com/i18next/i18next-intervalPlural-postProcessor/issues/206) and [#221](https://github.com/i18next/i18next-intervalPlural-postProcessor/issues/221)
