### ISSUE TITLE
postProcessor no longer works on i18next v21.*

### ISSUE THREAD

**Issue by lwhiteley** [i18next/i18next-intervalPlural-postProcessor#225]
## 🐛 Bug Report

The postprocessor no longer works on latest version of i18next

## To Reproduce

https://codesandbox.io/s/brave-cohen-1ll4k?file=/src/App.js

## Expected behavior

The postProcessor should work on i18next version v21.*

## Your Environment

see codesandbox.
You can easily switch the i18next version to before 21 to see the plurals are working below version 21

**Comment by adrai** [comment]
just use the correct suffixes:
![image](https://user-images.githubusercontent.com/1086194/136177235-4e3209e9-ce2f-4a7f-bedb-85fcbb07b099.png)
https://www.i18next.com/translation-function/plurals#singular-plural

**Comment by lwhiteley** [comment]
the same documentation pointed to also has the `_plural` suffix.
is the documentation incorrect then?

![Screenshot 2021-10-06 at 11 45 26 AM](https://user-images.githubusercontent.com/6108793/136180046-23cb7747-9718-4b1c-89af-28292f7e81f0.png)

**Comment by jamuhl** [comment]
yes...missed to update that for v21 -> https://www.i18next.com/translation-function/plurals#singular-plural
