### ISSUE TITLE
intervalPlural.setOptions doesn't work

### ISSUE THREAD

**Issue by claudiamatosa** [i18next/i18next-intervalPlural-postProcessor#82]
Hi all,

First of all, thank you for the great plugin! However, I was trying to set it up with a custom regular expression and ran into an issue. The setOptions function of the plugin doesn't work, as it's extending the options in the wrong order.

Line 36 of index.js:

```
  setOptions: function setOptions(options) {
    this.options = _extends({}, options, this.options);
  },
```

This means than the default options will always override the ones that were passed in.

Is there a specific reason why this happens? Otherwise, it should be:

```
this.options = _extends({}, this.options, options);
```

At the moment, it's possible to override the settings using `intervalPlural.options =`, but I'm not sure that is the intended behaviour.

**Comment by jamuhl** [comment]
thanks for reporting. fixed in i18next-intervalplural-postprocessor@0.2.3
